// <auto-generated />
using System;
using Exchanger.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exchanger.Web.Migrations
{
    [DbContext(typeof(ExchangerDbContext))]
    partial class ExchangerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Exchanger.Web.Data.Exchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FromAmount")
                        .HasColumnType("decimal(12,5)");

                    b.Property<string>("FromCurrency")
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("ToAmount")
                        .HasColumnType("decimal(12,5)");

                    b.Property<string>("ToCurrency")
                        .HasColumnType("varchar(3)");

                    b.HasKey("Id");

                    b.ToTable("ExchangesHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
